### ISSUE TITLE
unable to run mrs-sam

### ISSUE THREAD

**Issue by monperrus** [xblanc33/mrs-sam#17]
after "git clone" and "npm install", "nodejs index.js" fails with 

```
/tmp/mrs-sam/sitemap.js:1
(function (exports, require, module, __filename, __dirname) { class Node {
                                                              ^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/mrs-sam/index.js:12:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```
  An idea?

**Comment by xblanc33** [comment]
Which node version ?

**Comment by antoinevastel** [comment]
You need to update node doing the following:
sudo npm install -g npm 
sudo npm install -g n
sudo n stable

And if it still doesn't work after this:
sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/node

**Comment by monperrus** [comment]
or for debian `aptitude install -t experimental nodejs`

     $ nodejs --version
     v6.10.2
